import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/context/user-context";
import { ReactQueryProvider } from "@/context/react-query-provider";
import { GlobalNavbar } from "@/components/global-navbar";
import "@mdxeditor/editor/style.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body>
        <ReactQueryProvider>
          <UserProvider>
            <GlobalNavbar />
            {children}
          </UserProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
